version: "3.9"
services:
  app1: &app1
    image: app
    links:
      - "postgres:postgres"
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    environment:
      - CONFIG_FILE=./configs/backend/config_1.toml
      - SERVER_TYPE=server
  app2:
    <<: *app1
    ports:
      - "8083:8082"
    environment:
      - CONFIG_FILE=./configs/backend/config_2.toml
      - SERVER_TYPE=server
  app3:
    <<: *app1
    ports:
      -  "8084:8082"
    environment:
      - CONFIG_FILE=./configs/backend/config_3.toml
      - SERVER_TYPE=server
  mirror:
    image: app
    links:
      - "postgres:postgres"
    depends_on:
      - postgres1
    ports:
      - "8086:8082"
    environment:
      - SERVER_TYPE=mirror
      - CONFIG_FILE=./configs/backend/config_mirror.toml
  postgres:
    restart: always
    image: "postgres:alpine"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ppo
    volumes:
      - ./scripts/sql/script.sql:/docker-entrypoint-initdb.d/init.sql
  postgres1:
    restart: always
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ppo
    volumes:
      - ./scripts/sql/script.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    volumes:
      - .:/etc/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
  nginx:
    image: macbre/nginx-http3:1.23.1
    ports:
      - "443:443/tcp"
      - "443:443/udp"
      - "9090:9090/tcp"
      - "9090:9090/udp"
    links:
      - "app1:app1"
      - "app2:app2"
      - "app3:app3"
      - "mirror:app_mirror"
    volumes:
      - ./configs/nginx/nginx_http3.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/static
      - ./configs/certs/localhost/:/etc/nginx/ssl/
    depends_on:
      - app1
      - app2
      - app3
      - mirror