version: "3.9"
services:
  app:
    image: app
    links:
      - "postgres:postgres"
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    environment:
      - CONFIG_FILE=./configs/backend/config.toml

  postgres:
    restart: always
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bob
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ppo
    volumes:
      - ./scripts/sql/script.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: 'byjg/nginx-extras'
    ports:
      - "9090:9090"
    links:
      - "app:app"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/static
    depends_on:
      - app

